./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
