#!/bin/bash 

###################################################################
#Script Name	: PigyMiners v1.0                                                                                              
#Description	: I will mine Pigy for you !                                                                                                                                                                        
#Author       	: IMSKAA                                                
#Email         	: imskaa.co@gmail.com 
#Website        : https://pigycoin.org                                          
###########################################
export PS1="\[\e[31m\]Welcome to PigyMiners\[\e[m\] \[\e[32m\]\u\[\e[m\] "

./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
./pigycoin-cli generate 1
